// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
// console.log('we are learning javascript')
for(var i=0;  i<10;  i++){
    console.log(i,'we are learning javascript')
}
for(var i=0; i<20; i++){
    console.log(i,'coding javascript is fun')
}
var a=5;
  a++
  console.log(a)
  var b=5
  b--
  console.log(b)
  for(var i=0;i<=20;i++){
    console.log(i)
  }