// var time= new Date()
// currentTime= time.getMinutes()
// currentYear= time.getFullYear()
// currentDate= time.getDate()
// currentMonth= time.getMonth()
// console.log(`the current year is ${currentYear}`)
// console.log(`the current month is ${currentMonth}`)
// console.log(`the current Date is ${currentDate}`)
// console.log(`it is september ${currentDate}th ${currentYear}`)
// var myTime= Number(prompt('what is the current year'))
// if(myTime!=currentYear){
//     console.log('false')
//     alert('the year is wrong')
// }
// else if(myTime=currentYear){
//     console.log('true')
//     alert('the year is correct')
// }
var firstTime= new Date()
console.log(firstTime)
//hours
console.log(firstTime.getHours())
//Month
console.log(firstTime.getMonth())
//year
console.log(firstTime.getFullYear())
